### PR TITLE
Use golang-test:1.17-...again

### PR DESCRIPTION
**Pull request by oliver-goetz**
/bug

**What this PR does / why we need it**:
Unfortunately autobumper does not handle bumps with a prefix correctly.
Manual downgrade to golang 1.17

### CODE REVIEW

**Comment by oliver-goetz** [comment]
The PR now includes a proper fix. Image-builder creates a tag with a suffix instead of a prefix now.

**Review by timebertt — COMMENTED** [review]
Thank you!

**Review by timebertt — APPROVED** [review]
/lgtm

**Pull request merged**
