### PR TITLE
Add new metallb images

### PR DESCRIPTION
**Pull request by schrodit**
**Special notes for your reviewer**:
Adds new metallb images for the equinix cloud provider

### CODE REVIEW

**Comment by rfranzke** [comment]
So far, the images were coming from `quay.io`: https://github.com/gardener/gardener-extension-provider-equinix-metal/blob/dd2b0b98a9faef276be9218629cbea8c46d18b49/charts/images.yaml#L22-L29

Is this no longer the case? Can you please provide a proper PR description?

**Comment by schrodit** [comment]
> So far, the images were coming from `quay.io`: https://github.com/gardener/gardener-extension-provider-equinix-metal/blob/dd2b0b98a9faef276be9218629cbea8c46d18b49/charts/images.yaml#L22-L29
> 
> Is this no longer the case? Can you please provide a proper PR description?

yes currently they are coming from quay.io. But I wanted to update to the newer versions.
I thought that the guidance is that all images should be served via the gardener registry or is this only true for docker images?

**Comment by rfranzke** [comment]
Only for images from Docker Hub, see https://github.com/gardener/ci-infra/tree/fd6f0791bee478ba56ab7a325ed71aa26ca151fa/config/images#overview

**Comment by schrodit** [comment]
> Only for images from Docker Hub, see https://github.com/gardener/ci-infra/tree/fd6f0791bee478ba56ab7a325ed71aa26ca151fa/config/images#overview

ah ok sry for the distraction. Then I will close the PR.

**Pull request closed without merging**
