### PR TITLE
Remove etcd-druid nondistroless prow job

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**What this PR does / why we need it**:
Remove etcd-druid nondistroless prow job, since feature gate UseEtcdWrapper is promoted to GA by https://github.com/gardener/etcd-druid/pull/936.

**Which issue(s) this PR fixes**:
Fixes partially https://github.com/gardener/etcd-druid/issues/776

**Special notes for your reviewer**:
@oliver-goetz I am unaware of the prow job manifests under https://github.com/gardener/ci-infra/tree/master/config/jobs/etcd-druid/releases. Are these used only for running prow jobs against older release branches? If that's the case, I'm assuming I need not change them in this PR, correct? Please let me know.

### CODE REVIEW

**Review by ishan16696 — APPROVED** [review]
LGTM!!

**Comment by shreyas-s-rao** [comment]
@plkokanov @rfranzke PTAL. Not urgent, but would be nice to get rid of the now unnecessary prow job, since the feature gate on druid is moving to GA via https://github.com/gardener/etcd-druid/pull/936

**Pull request merged**
