### PR TITLE
Add gardener-cert-management repo to prow configs

### PR DESCRIPTION
**Pull request by MartinWeindel**
/kind enhancement

**What this PR does / why we need it**:
Add gardener-discovery-server repo to prow configs.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by oliver-goetz — COMMENTED** [review]
Thanks for your PR 🚀 
I'm glad to see another prow repository 😄 

I forgot one thing. You should create an [OWNERS](https://github.com/gardener/gardener-discovery-server/blob/main/OWNERS) and an [OWNERS_ALIASES](https://github.com/gardener/gardener-discovery-server/blob/main/OWNERS_ALIASES) file to `cert-management` repository which enlist its `reviewers` and `approvers`. I linked examples.

**Comment by MartinWeindel** [comment]
> I forgot one thing. You should create an [OWNERS](https://github.com/gardener/gardener-discovery-server/blob/main/OWNERS) and an [OWNERS_ALIASES](https://github.com/gardener/gardener-discovery-server/blob/main/OWNERS_ALIASES) file to `cert-management` repository which enlist its `reviewers` and `approvers`. I linked examples.

Thanks for the examples. So the [CODEOWNERS](https://github.com/gardener/cert-management/blob/master/CODEOWNERS) file used by GitHub (see [about-code-owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)) is then obsolete after the move?

**Comment by oliver-goetz** [comment]
Yes, CODEOWNERS should be obsolete then, because prow is overwriting the reviewers anyway.

/lgtm
/approve

**Pull request merged**
