### PR TITLE
Adapt `gardener/gardener` HA test jobs

### PR DESCRIPTION
**Pull request by rfranzke**
**What this PR does / why we need it**:
This PR adapts the `gardener/gardener` HA test jobs due to the changed introduced in https://github.com/gardener/gardener/pull/6914.

/kind enhancement

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6529

### CODE REVIEW

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
/hold
until https://github.com/gardener/gardener/pull/6914 is merged

**Pull request merged**
