### PR TITLE
Add branchprotector and config

### PR DESCRIPTION
**Pull request by timebertt**
Add branchprotector periodic job and configure it (currently, only for this repo).
Presubmits are always requirements for tide to merge if they run. If they run always, they are added to the branch protection rules as well.

Example test run: https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-prow-branchprotector/1466488973831442432

### CODE REVIEW

**Comment by timebertt** [comment]
/hold
Tide fails to merge this with
```
prow/tide-7b7b674955-4thgl[tide]: {"base-sha":"3a1d2856f470cc2dfab41ce71386bcf28fd8344f","branch":"master","component":"tide","controller":"sync","error":"branch needs to be configured to allow this robot to push: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.","file":"prow/tide/tide.go:1230","func":"k8s.io/test-infra/prow/tide.(*Controller).mergePRs","level":"debug","merge-targets":[9],"msg":"Merge failed.","org":"gardener","pr":9,"repo":"ci-infra","severity":"debug","sha":"819e4ab72d19bc12751845a861b95c67d2e9448c","time":"2021-12-03T06:58:38Z"}
```

**Comment by timebertt** [comment]
We can't exclude our tide GitHub App from the branch protection, see https://github.com/kubernetes/test-infra/issues/24530.
Hence, I dropped `enforce_admins: true` again to allow tide to merge PRs. Our goal should rather be to cut down the number of org/repo admins in general.

**Comment by timebertt** [comment]
/unhold
@rfranzke for another `/lgtm` :)

**Review by rfranzke — COMMENTED** [review]
/lgtm

**Comment by timebertt** [comment]
/unhold
And another try...
I applied the workaround from https://github.com/kubernetes/test-infra/issues/24530:

> As `branchprotector` doesn't touch the `apps` setting on the GitHub API, one can manually add the App to the branch protection rule and it won't be removed by `branchprotector` later on.

Also documented it in `config.yaml`.
Let's hope, this works now...

**Comment by rfranzke** [comment]
Sure, let's see then

/lgtm

**Pull request merged**
