### PR TITLE
Cleanup old gardener release branch jobs

### PR DESCRIPTION
**Pull request by timebertt**
/kind cleanup
/cc @plkokanov

### CODE REVIEW

**Comment by plkokanov** [comment]
Thanks a lot for addressing this! I guess you could also remove `skip_branches` for the control plane migration tests as well [here](https://github.com/gardener/ci-infra/blob/master/config/jobs/gardener/release/gardener-e2e-kind-migration-release.yaml#L10-L11) and [here](https://github.com/gardener/ci-infra/blob/4742e31cfa5aca8f0194349598d3de84abcf9a99/config/jobs/gardener/release/gardener-e2e-kind-migration-release.yaml#L52-L53).

**Comment by timebertt** [comment]
Thanks @plkokanov, done!

**Pull request merged**
