### PR TITLE
Added prow job to copy images

### PR DESCRIPTION
**Pull request by robinschneider**
/kind enhancement

**What this PR does / why we need it**:
This PR is the next step for #619 
Adds a prow job and script to copy images from DockerHub to GCR

**Special notes for your reviewer**:
List of images is incomplete, will be added in another PR in order to trigger the prow job.

### CODE REVIEW

**Review by timebertt — COMMENTED** [review]
/lgtm
/cc @oliver-goetz

**Comment by oliver-goetz** [comment]
There is a tiny bug in the volume mount definition of the prow job 😅 
```
  description: 'Pod can not be created: create pod test-pods/d513b9bb-c835-11ed-bd4c-0242ac110002
    in cluster gardener-prow-trusted: Pod "d513b9bb-c835-11ed-bd4c-0242ac110002" is
    invalid: spec.containers[0].volumeMounts[0].mountPath: Required value'
```

**Pull request merged**
